### ISSUE TITLE
Add original description on cascade MR

### ISSUE THREAD

**Issue by kakawait** [unblu/ucascade#27]
In our workflow, we always create an MR to solve a GitLab issue. Thus we're excepting that when MR is resolve that issue is automatically close if using [GitLab issue closing pattern](https://docs.gitlab.com/ee/administration/issue_closing_pattern.html)

The problem is that GitLab, only closing issue on default branch and GitLab could have only 1 default branch per repo.

In our case default branch is always latest version, here for example `3.0.0` (in following example, `3.0.0` is using meta/trunk branch `main` unlike `2.3.1` which is linked to `main/2.3.1`) . But if we've to fix on `2.3.1` we'll create a merge request on `main/2.3.1` with for example description containing 

```
fixes #XXX
```

and _ucascade_ will correctly create a merge request automatically but original description with `fixes #XXX` will not part of description of this newly created MR.

**I've already forked for our need but I'd like to know if is something that you're interested and thus I could propose a PR** (it could be configurable and disabled by default).

In our fork version MR will looks like (I've also done some _style_ update, like adding icon and emphasis)

<img width="902" alt="Screenshot 2024-05-14 at 18 27 23" src="https://github.com/unblu/ucascade/assets/275609/03d0a222-94e1-43e6-b0a1-bbb48d9ff31b">

by default original description is using built-in `<summary>` tag to be fold, but if you can unfold you could see (here our description is complete, is just short description :) because in our workflow most of information already part of issue. Thus there is no filtering on original description).
And if you've multiple level of cascade, it will always take the original (starting point) description not n-1!

<img width="885" alt="Screenshot 2024-05-14 at 18 27 29" src="https://github.com/unblu/ucascade/assets/275609/796012ec-e754-433a-85f6-a185023d59f4">

And so at then end, on the issue link will be conserved/cascaded and as soon that ucascade MR will reach our default branch the issue will be automatically close (in case there is an issue closing pattern)

<img width="910" alt="Screenshot 2024-05-14 at 18 41 28" src="https://github.com/unblu/ucascade/assets/275609/6c8ef65b-a120-4b16-b033-c829cb5a313e">

**Comment by jmini** [comment]
Thank you very much for this detailed issue.

We are not using GitLab issues yet, but this sounds a very useful addition to `ucascade`.

I don't think we need to make this configurable, since I can't imagine a case where the `fixes #XXX` mention should not be transferred to the next merge requests (the config flag could be added later if needed).

Also I think your styling of the MR description looks nicer and can be integrated.

So feel free to open a PR so that we can integrate your change in the main branch.

**Comment by kakawait** [comment]
> I don't think we need to make this configurable, since I can't imagine a case where the `fixes #XXX` mention should not be transferred to the next merge requests (the config flag could be added later if needed).

Is more my conservative spirit 😆 and to do not break existing usage.
I always think configuration, even if we choose, in this case, to put it to true by default unlike I just proposed is always better than hardcoded because each people have always different needs or workflows

I'll cleanup a bit my fork and push PR

**Comment by jmini** [comment]
After our exchange last week, we realized with @fbpe that our problem of GitLab not always closing issues in JIRA might be due to the same problem as the one you are describing. We are really interested to test if copying `Closes <Jira issue>` from the original MR in the cascade MR would help.

@kakawait is there something you can share in a PR, even if this is not finished or as clean as you would wish.

**Comment by kakawait** [comment]
Yes sorry. Few off days on France ☺️ 

I'll push PR tomorrow. Code is clean enough is more commit log to cleanup
